### ISSUE TITLE
Incompatible with Rails 4.2.0

### ISSUE THREAD

**Issue by hosamaly** [nakhli/angular_csrf#1]
Hi,

I've tried to run the specs on rails 4.2.0, but they are failing. I'm still investigating this issue. If you have any ideas, I'd be thankful if you could share them!

**Comment by nakhli** [comment]
Hey @hosamaly,

Indeed angular_csrf is not working with rails 4.2 (it is working fine for versions < 4.2) as they have changed the CSRF protection code. Did not investigate yet. PRs most welcome!

**Comment by hosamaly** [comment]
I could think of the following solution, which I presume would work for all current versions of Rails:

``` ruby
# before verified_request? is called:
params[request_forgery_protection_token] ||= request.headers[ANGULAR_CSRF_HEADER_NAME]
```

I didn't know where to put this code, so I worked around it in my `ApplicationController` as follows:

``` ruby
# in ApplicationController:
def form_authenticity_param
  # Handle Angular's way of sending CSRF tokens
  request.headers[AngularCsrf::ANGULAR_CSRF_HEADER_NAME] || super
end
```

**Comment by hosamaly** [comment]
Or, if you'd like to modify the code according to the version of Rails being used, you should call `valid_authenticity_token?(session, request.headers[ANGULAR_CSRF_HEADER_NAME])` instead of performing the equality comparison.

**Comment by nakhli** [comment]
Thank you for the code snippets @hosamaly, that was very helpful. I have just merged a fix and added [tests](https://travis-ci.org/Sinbadsoft/angular_csrf/builds/49107763) for rails 3.2, 4.1.8 and 4.2.

Preparing a new gem version that should solve the problem.

**Comment by nakhli** [comment]
New gem version [released](https://rubygems.org/gems/angular_csrf).

**Comment by hosamaly** [comment]
Thanks for the release @nakhli . But the change looks incompatible with Rails < 4.2.0. I'm not sure how you're testing it (because your Gemfile explicitly states rails 4.2.0), but the method [`valid_authenticity_token?`](https://github.com/rails/rails/commit/69fc0e1b5e6a3227576d67587c386142ef65854e#diff-c07f67f5a7946bbd9c38ba8283aea967R274), which was introduced in Rails 4.2.0, [does not exist](https://github.com/rails/rails/blob/v4.1.9/actionpack/lib/action_controller/metal/request_forgery_protection.rb) in Rails 4.1.9 or any previous version. Could you please validate that?

**Comment by nakhli** [comment]
I have added multiple rails versions in the Travis yaml : https://github.com/Sinbadsoft/angular_csrf/blob/master/.travis.yml
Test results: https://travis-ci.org/Sinbadsoft/angular_csrf/builds/49107763

Still, I think you are right, the rails version is not taken into account. I will investigate this.

**Comment by hosamaly** [comment]
I don't think it's sufficient to use `RAILS_VERSION` in an environment variable. I think you may create 3 different test apps, each with a different major version of Rails.

**Comment by equivalent** [comment]
yeah this gem looks to be bit unmaintained I recommend switching to https://github.com/jsanders/angular_rails_csrf
